spring:
  application:
    name: banking-api-knkcnw
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/bankdb
    user: postgres
    password: password
    enabled: true
    create-schemas: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  twilio:
    account:
      sid: your_twilio_account_sid
    auth:
      token: your_twilio_auth_token
    phone:
      number: +1234567890
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true


sendgrid:
  api:
    key: YOUR_SENDGRID_API_KEY